org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=jei_tag_groups
mod_name=JEI Tag Groups
mod_license=All Rights Reserved
mod_version=1.20.1-forge-1.3fix
mod_group_id=com.jei_tag_groups
mod_authors=hp
mod_description=Groups JEI item entries by configured item tags and items
jei_version=15.48.0.179
jei_version_range=[15.48.0.179,)
