org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1.248
neoforge_version_range=[21.1,)
loader_version_range=[4,)
mod_id=jei_tag_groups
mod_name=JEI Tag Groups
mod_license=All Rights Reserved
mod_version=1.21.1-neoforge-1.2fix
mod_group_id=com.jei_tag_groups
mod_authors=hp
mod_description=Groups JEI item entries by configured item tags and items
jei_version=19.43.0.393
jei_version_range=[19.43.0,)
